version: '3.8'

services:
  api:
    build:
      context: ./
      dockerfile: docker/api.Dockerfile
    env_file:
      - .env
    ports:
      - "80:80"
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy


  mariadb:
    image: mariadb:11.2
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    healthcheck:
      interval: 10s
      retries: 5
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized"
        ]
      timeout: 10s
    volumes:
      - db_mariadb:/var/lib/mysql:Z

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    env_file:
      - .env


  flower:
      image: mher/flower
      command: celery --broker=redis://redis:6379/0 flower --port=5555
      ports:
        - "5555:5555"
      depends_on:
        - api
        - redis

volumes:
  db_mariadb:



