"""Create packagedb table

Revision ID: 9e9fd6350e0c
Revises: b5c0ba2502ee
Create Date: 2024-02-08 18:32:59.109941

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9e9fd6350e0c"
down_revision: Union[str, None] = "b5c0ba2502ee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "packagedbs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("package_type", sa.String(length=100), nullable=False),
        sa.Column("package_cost", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("shipping_cost", sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column("user_session_id", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["package_type"],
            ["packagetypedbs.name"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("packagedbs")
    # ### end Alembic commands ###
